### ISSUE TITLE
nice !

### ISSUE THREAD

**Issue by smolleyes** [ghondar/react-native-vlc-player#1]
hello

great project ! keep up the good work :)

2 questions:
- have something to do to play http streams ? seems playing only local files (perfectly)
- ios version planned ? 

thanks !

**Comment by ghondar** [comment]
@smolleyes 

1. Done - 161dc6a86b08b7925d7445e1bddbd705a93b6061
2. I know very little objective-c, but i know another vlc wrapper for ios, [react-native-vlcplayer](https://github.com/xiongchuan86/react-native-vlcplayer)

 Thnks for suggestions 👍

**Comment by smolleyes** [comment]
hello @ghondar 

just update the mainactivity file, the app "crash now" won t play url and it just freeze :p 

can t use the back button on my phone or anything else  :)

**Comment by smolleyes** [comment]
hummm

decode fail on many mp4, i see that in logcat, strange... trying an ogv now it works but very slowly

i look the doc for vlclib java :p

**Comment by ghondar** [comment]
@smolleyes  can you give me a url to try from my pc?

**Comment by smolleyes** [comment]
ok hevc and all my isp tv channels works well it s all i need :) 

i build an app to get this tv channels thru a small node transconding server 

can try this link from my transcoding server if you want (hevc/opus)

http://82.234.5.89:8890/?file=rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=997&flavour=ld&bitrate=360&screen=616x360&vcodec=libx265&acodec=libopus

![image](https://cloud.githubusercontent.com/assets/200256/16889568/af7f1e48-4ae7-11e6-8d43-a2991fcc93f2.png)


i think this module need 2-3 things

- fix the ratio in portrait mode 
- add default size as parameters when loading the player and add button for fullscreen
- maybe buttons to choose the aspect ratoo too :)

and it s ok for me (will try to do it too)

**Comment by smolleyes** [comment]
http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4

this was the failing video

**Comment by ghondar** [comment]
What phone are you using?
from genymotion big_buck_bunny.mp4 play without problems

**Comment by ghondar** [comment]
yep, I know that many things to add is missing, It's just that now I am not with time to do so.
If you could do it would be great :D

**Comment by smolleyes** [comment]
i run it durectly on my one plus one  / exodus 6.0.1 rom ...

**Comment by smolleyes** [comment]
[ 07-16 00:13:20.524 23176:29607 W/VLC      ]
[aec548ac] mp4 stream: unknown box type sdp  (incompletely loaded)

[ 07-16 00:13:20.524 23176:29607 W/VLC      ]
[aec548ac] mp4 stream: unknown box type hinf (incompletely loaded)

[ 07-16 00:13:20.524 23176:29607 W/VLC      ]
[aec548ac] mp4 stream: unknown box type rtp  (incompletely loaded)

[ 07-16 00:13:21.480 23176:29607 W/VLC      ]
[9ca553ac] mp4 demux: elst box found

[ 07-16 00:13:21.480 23176:29607 W/VLC      ]
[9ca553ac] mp4 demux: STTS table of 1 entries

**Comment by smolleyes** [comment]
i ll try to add a button first..., i develop ony with js now... python/bash before

i suck on java an 0 on objective but will try :)

**Comment by smolleyes** [comment]
what s the version of your libvlc ?

**Comment by ghondar** [comment]
it's 1.9.8 [vlc-android-sdk](https://github.com/mrmaffen/vlc-android-sdk)

I just try it from a galaxy mini s3 and played fine big_buck_bunny.mp4 but your server i think that it no longer works

**Comment by smolleyes** [comment]
trying to build e newer libvlc now :p it s building...

yep it s down now :)

**Comment by smolleyes** [comment]
hello

any update on ios version :p ?

thanks !

**Comment by alaj** [comment]
Nice work !
Can this play RTSP streaming video ?
Such as " rtsp://192.168.1.2/video "

**Comment by kingctan** [comment]
nice work! keep up! 
-:)

**Comment by ghondar** [comment]
@smolleyes i'm sorry but i don't know objective-c

@alaj yes, you can :)

@kingctan  thanks :D

**Comment by alaj** [comment]
@ghondar It works, THANKS!!

**Comment by ghondar** [comment]
@alaj you are welcome :D
