### ISSUE TITLE
missing 'Platform' refrence from 'react-native'

### ISSUE THREAD

**Issue by hoseiniraji** [ghondar/react-native-vlc-player#22]
Hi
first of all, thank you for this great job!

it seems that there is a bug on changing orientation.
I added "Platform" reference at top of  src/Orientation.js by changing 

`import { DeviceEventEmitter, NativeModules } from 'react-native'`

to

`import { DeviceEventEmitter, NativeModules , Platform } from 'react-native'`

and it fixed.

I hope this can help other fellas running into this problem.
BTW i'm using this library in a react native project with expo v35.0.

best regards

**Comment by ghondar** [comment]
@hoseiniraji  you're right i just added 11055da5a4de0fb9eab3a7e4ed34a655b73a7960
